### ISSUE TITLE
Epic: Delivering new ACS data to OSE - Aug 2022 

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-factfinder#221]
We need to deliver already processed ACS data to OSE to update the [PFF App](https://popfactfinder.planning.nyc.gov/#12.25/40.724/-73.9868) in sprints O and P.  This work needs to be done in sprint N.

Source data: 2 Excel files sent by EM: 2006 - 2010 and 2016 - 2020
Target schema: [2010](https://cloud.digitalocean.com/spaces/edm-publishing?i=266877&path=db-factfinder%2Facs%2Fyear%3D2010%2Fgeography%3D2010_to_2020%2F) - replace, but do not delete current file and create new folder for 2020 (can use [2019](https://cloud.digitalocean.com/spaces/edm-publishing?i=266877&path=db-factfinder%2Facs%2Fyear%3D2019%2Fgeography%3D2010_to_2020%2F) file as reference)

Known tasks:

- [x] Ingest and store source data.  Decide where to store source data.  Digital Ocean or GitHub.
- [x] Transform data from Excel spreadsheets into csv layout
- [x] Implement lookup tables to provide values needed in PFF
     - [ ] Geo lookup [2010](https://github.com/NYCPlanning/db-factfinder/tree/dev/factfinder/data/lookup_geo/2010) and [2020](https://raw.githubusercontent.com/NYCPlanning/db-factfinder/dev/factfinder/data/lookup_geo/2020/lookup_geo.csv)
     - [ ] PFF variable lookup [2010](https://github.com/NYCPlanning/db-factfinder/blob/dev/factfinder/data/acs/2010/metadata.json) and [2019](https://github.com/NYCPlanning/db-factfinder/tree/dev/factfinder/data/acs/2019).  Create new file for 2020 data
- [x] Create a questions issue to communication with Population.  See old issue as reference [here](https://github.com/NYCPlanning/db-factfinder/issues/41)

**Comment by SashaWeinstein** [comment]
created the questions issue #223
